name: gekim
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - -r requirements.txt  # Install other dependencies through pip